from __future__ import annotations

from pipeline_common import QUESTION_FIELDS, read_jsonl, write_csv


def row(
    question_id: str,
    doc_id: str,
    question: str,
    answer: str,
    question_type: str,
    gold_node_ids: str,
    gold_pages: str,
    gold_modalities: str,
    evidence_note: str,
) -> dict[str, str]:
    return {
        "question_id": question_id,
        "doc_id": doc_id,
        "question": question,
        "answer": answer,
        "question_type": question_type,
        "gold_node_ids": gold_node_ids,
        "gold_pages": gold_pages,
        "gold_modalities": gold_modalities,
        "evidence_note": evidence_note,
    }


ROWS = [
    row(
        "Q001",
        "AI综述类",
        "这篇 AI 综述如何划分 Multimodal RAG for document understanding 的 taxonomy，并且还关注了哪些增强方向？",
        "它按 domain、retrieval modality 和 granularity 建立 taxonomy，同时综述 graph structures 和 agentic frameworks 等增强方向。",
        "文本事实",
        "T_AI综述类_1_3",
        "1",
        "text",
        "摘要节点说明了 taxonomy 维度和 graph/agentic 增强方向。",
    ),
    row(
        "Q002",
        "AI综述类",
        "结合 Table 1，M3DocVQA 与 OpenDocVQA 在页数和 visual tokens 规模上有什么差异？",
        "M3DocVQA 约 40K pages、41M visual tokens；OpenDocVQA 约 206K pages、206M visual tokens，后者规模明显更大。",
        "表格问答",
        "T_AI综述类_2_1;T_AI综述类_2_3",
        "2",
        "text;table",
        "Table 1 内容和正文解释共同说明代表性 benchmark 的规模。",
    ),
    row(
        "Q003",
        "AI综述类",
        "Table 2 比较多模态 RAG 方法时用了哪些维度？",
        "包括 venue、backbone LLM/VLM、vision encoder、training status、OCR integration、domain scope、retrieval modality、retrieval granularity、graph incorporation 和 agent usage。",
        "表格问答",
        "T_AI综述类_4_1;C_AI综述类_4_1;TB_AI综述类_4_1;T_AI综述类_4_2",
        "4",
        "text;caption;table",
        "表注、表格节点和正文解释共同给出 Table 2 的比较维度。",
    ),
    row(
        "Q004",
        "AI综述类",
        "早期 OCR-based 检索索引与 DSE/ColPali 这类视觉语言检索方法相比，主要差别是什么？",
        "早期方法先对所有文档 OCR 后建立文本索引，计算代价高且低效；DSE、ColPali 等直接利用视觉语言模型做文档检索，更适合视觉丰富文档。",
        "跨模态综合",
        "T_AI综述类_4_4",
        "4",
        "text",
        "正文比较了 OCR 文本索引与 vision-language retrieval 的路线差异。",
    ),
    row(
        "Q005",
        "AI综述类",
        "Figure 4 相关段落说明，page-level retrieval 为什么不足，fine-grained retrieval 想解决什么问题？",
        "page-level retrieval 把页面作为原子单位，不能建模表格、图表和布局线索；fine-grained retrieval 进一步在页内检索组件或建立细粒度 grounding。",
        "图文一致性",
        "C_AI综述类_6_1;F_AI综述类_6_1;T_AI综述类_6_4;T_AI综述类_6_5",
        "6",
        "caption;figure;text",
        "Figure 4 图注与正文共同解释 retrieval granularity 的变化。",
    ),
    row(
        "Q006",
        "AI综述类",
        "数据集表中，PlotQA、ChartQA 和 DocVQA 分别体现了什么样的视觉文档内容类型？",
        "PlotQA 面向 plot/chart 类图表，ChartQA 面向 chart question answering，DocVQA 面向含文本/表格等视觉文档理解。",
        "表格问答",
        "TB_AI综述类_8_1;T_AI综述类_8_1",
        "8",
        "table;text",
        "第 8 页数据集表和表注说明了不同 dataset 的内容类型。",
    ),
    row(
        "Q007",
        "AI综述类",
        "M3DocVQA、VisDoMRAG 和 VDocRAG 在评测场景上相对单文档任务有什么扩展？",
        "它们扩展到 cross-document open-domain scenarios，分别使用 M3DocVQA、VisDoMBench 和 OpenDocVQA 等进行开放域跨文档评估。",
        "文本事实",
        "T_AI综述类_8_3",
        "8",
        "text",
        "正文说明这些 benchmark 从单文档扩展到跨文档开放域场景。",
    ),
    row(
        "Q008",
        "AI综述类",
        "BBox-DocVQA 的目标是什么，它为什么比只检索相关页面更细？",
        "BBox-DocVQA 提供带 bounding-box grounding 的 DocVQA 数据，用于监督 spatial reasoning 和 evidence localization，比只返回页面更关注具体视觉元素定位。",
        "证据定位",
        "T_AI综述类_8_4;TB_AI综述类_23_1",
        "8;23",
        "text;table",
        "第 8 页介绍 BBox grounding，第 23 页讨论只把页面当原子单元的指标局限。",
    ),
    row(
        "Q009",
        "AI综述类",
        "这篇综述举了哪些 Multimodal RAG 的应用领域示例？",
        "包括金融问答、科学研究文献、多模态科学语料和社会科学调查/信息图解释等应用。",
        "文本事实",
        "T_AI综述类_8_5;T_AI综述类_8_7",
        "8",
        "text",
        "应用段落列举 finance、scientific research 和 social sciences 等领域。",
    ),
    row(
        "Q010",
        "AI综述类",
        "Top-K Accuracy 这类检索指标衡量什么？为什么在多模态文档中还需要更细的定位指标？",
        "Top-K Accuracy 衡量 top-K 检索结果是否命中相关证据；但复杂文档中页面不是最小证据单元，还需要定位表格、图、区域或视觉元素。",
        "跨模态综合",
        "TB_AI综述类_20_1;TB_AI综述类_23_1",
        "20;23",
        "table;text",
        "公式节点给出 Top-K Accuracy 定义，后文说明页面级 Recall@K 的局限。",
    ),
    row(
        "Q011",
        "医保欺诈类",
        "表 1 的样本基本情况说明，该研究总样本量、欺诈样本数、欺诈占比和建模特征数分别是多少？",
        "总样本量为 16000，欺诈样本 793，占比 4.96%，建模特征数为 110。",
        "表格问答",
        "TB_医保欺诈类_9_3",
        "9",
        "table",
        "表 1 直接给出样本规模、欺诈比例和建模特征数。",
    ),
    row(
        "Q012",
        "医保欺诈类",
        "表 2 中哪些变量类别用于刻画医保欺诈风险？各自代表变量是什么？",
        "变量类别包括就诊行为、费用峰值、费用结构、支付救助和规则偏离；代表变量包括一天去两家医院的天数、月统筹金额_MAX、治疗费用占比、医疗救助医院申请_SUM 和规则命中次数。",
        "表格问答",
        "TB_医保欺诈类_10_2",
        "10",
        "table",
        "表 2 将变量类别、代表变量和业务含义放在同一表格中。",
    ),
    row(
        "Q013",
        "医保欺诈类",
        "结合差异分析正文和图 4，为什么作者认为欺诈风险不是单一变量造成的？",
        "因为欺诈样本在就诊行为、费用峰值、费用结构和支付救助等多个变量上整体偏离，且相关图显示变量之间存在一定相关性但未完全重合。",
        "图文一致性",
        "TB_医保欺诈类_12_1;C_医保欺诈类_13_1;F_医保欺诈类_13_1",
        "12;13",
        "table;caption;figure",
        "第 12 页正文说明多维偏离，第 13 页图 4 为 Spearman 相关特征图。",
    ),
    row(
        "Q014",
        "医保欺诈类",
        "疑似欺诈对象被概括为哪四类典型画像？",
        "跨机构高频型、高费用峰值型、治疗与材料异常型、支付救助偏离型。",
        "文本事实",
        "TB_医保欺诈类_14_1",
        "14",
        "table;text",
        "统计画像段落列出四类典型画像及其含义。",
    ),
    row(
        "Q015",
        "医保欺诈类",
        "从统计解释到预测排序的模型链路是如何安排的？",
        "先用 Logistic 回归识别风险因素方向，再用随机森林检验非线性增益，选择 LightGBM 作为主模型，最后用规则分、同群偏离分和综合风险评分转化为预警等级与证据条目。",
        "跨模态综合",
        "TB_医保欺诈类_15_1",
        "15",
        "table;text",
        "该段描述模型链路与治理闭环的对应关系。",
    ),
    row(
        "Q016",
        "医保欺诈类",
        "综合风险分的最优权重组合是什么？它在治理闭环中承担什么作用？",
        "最优权重组合为 (0.90, 0.05, 0.05)，用于把模型概率、规则知识和同群偏离信息压缩为统一监管评分，支持风险分层、证据卡片和差异化处置。",
        "表格问答",
        "TB_医保欺诈类_21_1",
        "21",
        "table;text",
        "第 21 页给出综合风险分权重和定位说明。",
    ),
    row(
        "Q017",
        "医保欺诈类",
        "表 5 中 LightGBM 与 XGBoost 的主要差异是什么？为什么最终选择 LightGBM？",
        "XGBoost 的 Recall 更高，但 LightGBM 的 PR-AUC、F1、Precision 和 Top5% P@K 表现更优，因此更兼顾识别效率、误报控制和监管核查命中。",
        "表格问答",
        "TB_医保欺诈类_22_2;TB_医保欺诈类_23_1",
        "22;23",
        "table;text",
        "表 5 数值和正文共同解释模型选择依据。",
    ),
    row(
        "Q018",
        "医保欺诈类",
        "表 6 对比 Wang 等方法复现与本文方法时，本文方法在哪些方面更适合监管场景？",
        "本文方法 Recall 和 Top5% P@K 更优，运行时间约 80s，仅为对比方法 500s 的一小部分，更适合核查资源聚焦和部署效率。",
        "表格问答",
        "TB_医保欺诈类_23_3;TB_医保欺诈类_24_1",
        "23;24",
        "table;text",
        "表 6 给出数值，第 24 页正文解释效率和监管价值。",
    ),
    row(
        "Q019",
        "医保欺诈类",
        "表 7 中哪类高风险组合的欺诈率最高？它相对全样本基线约是多少倍？",
        "跨机构高频 + 治疗占比异常的欺诈率最高，为 81.82%，相对基线约 16.50 倍。",
        "表格问答",
        "TB_医保欺诈类_27_1",
        "27",
        "table",
        "表 7 列出了不同高风险组合的欺诈率和相对基线倍数。",
    ),
    row(
        "Q020",
        "医保欺诈类",
        "结合风险分层表和证据卡片示例，高风险层与单个样本证据卡片分别能提供什么监管信息？",
        "风险分层表显示高风险层有 48 个样本、42 个欺诈样本、欺诈率 87.50%；证据卡片示例给出样本 1174 的风险分数 0.9832、命中规则和关键特征贡献。",
        "跨模态综合",
        "TB_医保欺诈类_28_2;TB_医保欺诈类_29_1",
        "28;29",
        "table;text",
        "风险分层表和图 16 证据卡片说明模型输出如何转为可核查证据。",
    ),
    row(
        "Q021",
        "化学类",
        "摘要中 6-methyl-2-formylpyridine 与 3-methyl-2-formylpyridine 分别导致形成什么 cage/prism 结构？",
        "6-methyl-2-formylpyridine 形成 [CuI12L6]12+ pseudo-hexagonal prismatic cage；3-methyl-2-formylpyridine 因 steric clashes 形成 [CuI8L4]8+ rectangular open prism。",
        "文本事实",
        "T_化学类_1_1;T_化学类_1_2",
        "1",
        "text",
        "摘要对两种 aldehyde component 的结构结果进行了对比。",
    ),
    row(
        "Q022",
        "化学类",
        "Figure 1 的图注和正文给出了 cage 1 的哪些结构和 DOSY 信息？",
        "Figure 1 展示 CuI12L6 pseudo-hexagonal prism 1 的自组装、1H DOSY 谱和 X-ray 结构；DOSY 给出 D=3.70×10^-10 m2/s，对应 solvodynamic radius 34.6 Å。",
        "图表理解",
        "C_化学类_3_1;F_化学类_3_1;T_化学类_3_1",
        "3",
        "caption;figure;text",
        "图注说明 Figure 1 的面板，正文给出 DOSY 数值。",
    ),
    row(
        "Q023",
        "化学类",
        "Figure 2 与正文共同说明 cage 1 由哪些 secondary interactions 稳定？数量大约是多少？",
        "cage 1 由约 32 个 C-H...π interactions 和 12 个 aromatic stacking interactions 协同稳定。",
        "图文一致性",
        "C_化学类_4_1;F_化学类_4_1;T_化学类_3_2;T_化学类_4_1",
        "3;4",
        "caption;figure;text",
        "Figure 2 标出 π...π 和 C-H...π interactions，正文给出数量。",
    ),
    row(
        "Q024",
        "化学类",
        "为什么把 methyl substituents 移到 3-position 会阻碍形成 cage 1？",
        "因为 3-position bulky substituents 会与邻近 naphthylene moieties 产生严重 steric clashes，并破坏稳定 cage 1 的 C-H...π interactions。",
        "跨模态综合",
        "T_化学类_4_2;T_化学类_4_3;T_化学类_4_4",
        "4",
        "text",
        "正文先指出 3-position 氢参与相互作用，再说明假想结构中的 steric clashes。",
    ),
    row(
        "Q025",
        "化学类",
        "Figure 3 中 rectangular open prism 2 是如何组装的？DOSY 和 ESI-MS 支持什么组成判断？",
        "它由 subcomponent A、3-methyl-2-formylpyridine C 和 CuI(MeCN)4OTf 自组装而成；DOSY 对应 33.4 Å，ESI-MS 支持 [CuI8L4]8+ 组成。",
        "图表理解",
        "C_化学类_5_1;F_化学类_5_1;T_化学类_4_6;T_化学类_5_1",
        "4;5",
        "caption;figure;text",
        "Figure 3 图注和正文共同给出组装路线、DOSY 和 ESI-MS 信息。",
    ),
    row(
        "Q026",
        "化学类",
        "Figure 3 的结构说明中，prism 2 的 3-methyl groups 位于哪里，为什么这有助于解释其结构稳定性？",
        "3-methyl groups 朝向 void areas，避免与其他 moieties 接触，因此处在 sterically unhindered locations，有利于 rectangular open prism 2 稳定存在。",
        "图文一致性",
        "F_化学类_5_1;T_化学类_5_1;T_化学类_5_3",
        "5",
        "figure;text",
        "Figure 3 结构图和正文解释 methyl groups 的空间位置。",
    ),
    row(
        "Q027",
        "化学类",
        "Figure 4 描述的 2 到 1' 的 structural reconfiguration 需要替换多少个 aldehyde residues？",
        "每个 [CuI12L6]12+ cage 中约 8 个 3-methyl-2-formylpyridine residues 被 6-methyl-2-formylpyridine 替换。",
        "图表理解",
        "C_化学类_7_1;F_化学类_7_1;T_化学类_7_1;T_化学类_7_3",
        "7",
        "caption;figure;text",
        "Figure 4 图注和结论段都说明了 8 out of 24 residues 的替换。",
    ),
    row(
        "Q028",
        "化学类",
        "这篇化学论文的核心设计原则是什么？",
        "通过平衡有利的 secondary interactions 与 steric effects，可以控制 metal-organic cage 的结构并实现可控 reconfiguration。",
        "文本事实",
        "T_化学类_7_3;T_化学类_1_6",
        "1;7",
        "text",
        "引言和结论共同说明非共价相互作用与位阻调控 cage architecture。",
    ),
    row(
        "Q029",
        "化学类",
        "cage 1 和 prism 2 的 DOSY 尺寸信息如何相互印证结构差异？",
        "cage 1 的 solvodynamic radius 为 34.6 Å；prism 2 的 solvodynamic diameter 为 33.4 Å，后者尺寸更小，与 [CuI8L4]8+ open prism 组成一致。",
        "跨模态综合",
        "T_化学类_3_1;T_化学类_4_6",
        "3;4",
        "text",
        "两个 DOSY 结果分别支持 cage 1 与 prism 2 的尺寸和组成差异。",
    ),
    row(
        "Q030",
        "化学类",
        "Figure 2 中 π...π 和 C-H...π interactions 分别用什么视觉标记突出？",
        "π...π interactions 的 interplanar distances 用蓝色、centroid-centroid distances 用绿色；C-H...π 的 hydrogen-centroid distances 用粉色突出。",
        "证据定位",
        "C_化学类_4_1;T_化学类_4_1",
        "4",
        "caption;text",
        "Figure 2 图注及紧随其后的说明给出颜色标记。",
    ),
    row(
        "Q031",
        "工程热物理类",
        "这篇工程热物理论文研究的冷却对象和数值方法是什么？",
        "研究垂直自由射流冲击受热圆盘/圆柱热体的传热与流动，使用 ANSYS Fluent、VOF 方法、k-epsilon 湍流模型和能量方程。",
        "文本事实",
        "T_工程热物理类_2_3;T_工程热物理类_12_1",
        "2;12",
        "text",
        "摘要和结论概括了研究对象与数值方法。",
    ),
    row(
        "Q032",
        "工程热物理类",
        "摘要中铜热体与不锈钢组合热体的最大热通量有什么差别？",
        "铜热体在滞止区边缘最大热通量为 2.5 MW/m2；与不锈钢组合时约为 1.5 MW/m2。",
        "文本事实",
        "T_工程热物理类_2_4;T_工程热物理类_2_5",
        "2",
        "text",
        "摘要直接给出两种材料条件下的最大热通量。",
    ),
    row(
        "Q033",
        "工程热物理类",
        "Figure 1 和 Figure 2 相关段落分别展示了什么几何信息？",
        "Figure 1 展示 Zeitoun and Ali 实验几何的三维视图和侧视图；Figure 2 展示本文模拟的两个轴对称 2D layout。",
        "图文一致性",
        "T_工程热物理类_4_3;T_工程热物理类_4_5;T_工程热物理类_4_6;T_工程热物理类_5_1",
        "4;5",
        "text;figure",
        "正文中的图题和几何描述对应 Figure 1 与 Figure 2。",
    ),
    row(
        "Q034",
        "工程热物理类",
        "网格无关性表中，为什么 mesh 3 被认为适合用于后续研究？",
        "mesh 3 有 28,220 个单元、0.05 mm 第一层厚度和 13 层液相网格，Nu=839.4，偏差为 -4.8%，相比更密网格精度已基本稳定。",
        "表格问答",
        "T_工程热物理类_6_5;TB_工程热物理类_7_1",
        "6;7",
        "text;table",
        "网格研究正文和 Table 1 数值共同说明 mesh 3 的选择。",
    ),
    row(
        "Q035",
        "工程热物理类",
        "Table 2 中 case 3 与 case 6 的材料/几何差异是什么？",
        "case 3 是 Figure 2(b)、L1=50 mm、单层 Copper；case 6 是 Figure 2(b)、L1=3 mm、L2=50 mm、Stainless steel + Copper 组合。",
        "表格问答",
        "TB_工程热物理类_7_2",
        "7",
        "table",
        "Table 2 列出不同 case 的 geometry、L1/L2、热边界和材料。",
    ),
    row(
        "Q036",
        "工程热物理类",
        "Table 3 中铜、镍和 304 不锈钢的导热系数如何排序？",
        "Copper 最高，为 388 W/m·K；Nickel 为 91 W/m·K；Stainless steel 304 最低，为 16 W/m·K。",
        "表格问答",
        "TB_工程热物理类_7_3",
        "7",
        "table",
        "Table 3 给出材料密度、比热和导热系数。",
    ),
    row(
        "Q037",
        "工程热物理类",
        "Figure 5 的结果说明材料和几何变化对平均 Nusselt number 有什么影响？",
        "虽然材料和几何会显著改变局部热通量和温度分布，但平均 Nusselt number 在纯水和不同浓度纳米流体下几乎不受影响。",
        "图文一致性",
        "T_工程热物理类_8_3;T_工程热物理类_8_4;T_工程热物理类_9_1",
        "8;9",
        "text;figure",
        "Figure 5 图题和正文共同解释平均 Nu 对 case 变化不敏感。",
    ),
    row(
        "Q038",
        "工程热物理类",
        "Figure 6 与 Figure 7 所对应的局部热通量/温度结论是什么？",
        "材料和厚度的细微改变会显著影响热通量分布；case 6 更趋向均匀热通量，而 case 3 的铜厚板温度分布最均匀，最大热通量从 case 6 到 case 3 约增加 40%。",
        "跨模态综合",
        "T_工程热物理类_8_4;T_工程热物理类_8_7;T_工程热物理类_8_8;T_工程热物理类_10_1;T_工程热物理类_10_2",
        "8;10",
        "text;figure",
        "正文解释 Figure 6 的热通量和 Figure 7 的温度分布。",
    ),
    row(
        "Q039",
        "工程热物理类",
        "热线 heatline 分析显示不同材料厚度如何影响能量传输路径？",
        "较高热阻会使能量线更平坦；铜厚层会形成较小斜率，侧边加热会使热量沿更长路径到达滞止区，而铜与薄不锈钢组合可接近更均匀热通量。",
        "图文一致性",
        "T_工程热物理类_11_1;T_工程热物理类_11_3;T_工程热物理类_11_5",
        "11",
        "text;figure",
        "Figure 10 相关段落描述 heatline 和能量传输路径。",
    ),
    row(
        "Q040",
        "工程热物理类",
        "结论中作者如何评价 uniform heat flux 假设？",
        "作者认为实验室中难以在 impinging wall 上获得真正均匀热通量，热通量会从滞止区到边缘出现大范围分布；材料和几何主要影响热通量/温度分布而非射流整体特征。",
        "文本事实",
        "T_工程热物理类_12_3;T_工程热物理类_12_5",
        "12",
        "text",
        "结论总结了 uniform heat flux 假设的局限和材料几何影响。",
    ),
    row(
        "Q041",
        "材料类",
        "这篇材料论文提出的 high-throughput workflow 主要用于什么目标？",
        "用于高通量表征和分析 compositionally graded magnetic films，以指导低或无 critical elements 的 hard magnetic materials 设计。",
        "文本事实",
        "TB_材料类_1_3;T_材料类_1_2",
        "1",
        "table;text",
        "摘要和引言说明 workflow 的目标和材料应用场景。",
    ),
    row(
        "Q042",
        "材料类",
        "为什么 combinatorial high-throughput approach 对多元材料尤其重要？",
        "因为多元材料的元素组合数量随元素数指数增长，传统 trial-and-error 既耗时又耗资源，高通量方法可加速并降低探索成本。",
        "文本事实",
        "T_材料类_1_2;T_材料类_1_4",
        "1",
        "text",
        "引言解释了传统试错和多元组合空间的限制。",
    ),
    row(
        "Q043",
        "材料类",
        "论文中哪些高通量表征技术被用于 composition、thickness、magnetic properties 和 crystal structure？",
        "EDX 用于 composition，mechanical profilometer 用于 thickness，MOKE microscopy 用于 magnetic properties，XRD 用于 phase identification/crystal structure。",
        "跨模态综合",
        "T_材料类_3_10;T_材料类_4_1",
        "3;4",
        "text",
        "方法概述段落列出不同测量技术及其对应属性。",
    ),
    row(
        "Q044",
        "材料类",
        "Figure 3 相关说明中，EDX composition mapping 输出了哪些可视化结果？",
        "输出包括某一位置的元素谱图，以及 wafer-level vanadium content heatmap。",
        "图文一致性",
        "T_材料类_4_6;T_材料类_4_7;T_材料类_5_1",
        "4;5",
        "text;figure",
        "Figure 3 图题和正文说明 EDX 谱图与 V 含量热图。",
    ),
    row(
        "Q045",
        "材料类",
        "Figure 4/表格节点说明 profilometry 厚度测量需要哪些步骤和输出？",
        "需要图案化薄膜、化学刻蚀形成台阶，使用 mechanical profilometer 测量每个 cell；输出 raw/fitted data、extracted heights 和 thickness heatmap。",
        "图文一致性",
        "T_材料类_5_7;T_材料类_5_8;TB_材料类_5_1",
        "5",
        "text;table;figure",
        "Figure 4 相关文本和表格节点描述厚度测量流程及热图输出。",
    ),
    row(
        "Q046",
        "材料类",
        "Figure 9 的 ternary diagrams 如何把 composition、coercivity 和 phase fraction 结合起来？",
        "Figure 9 将 position-dependent composition maps 与 coercivity、Sm(Fe,V)12 phase fraction 等信息结合，形成三元图以寻找成分-相-磁性能之间的关系。",
        "图表理解",
        "T_材料类_10_5;C_材料类_10_1;F_材料类_10_1",
        "10",
        "text;caption;figure",
        "Figure 9 图注和正文说明三元图由 composition/coercivity/phase fraction 派生。",
    ),
    row(
        "Q047",
        "材料类",
        "为什么 Figure 9 的 ternary diagrams 可能受到 Fe2Ta 和 Sm-oxide phases 的偏置？",
        "因为退火后形成了 Ta 和 O 相关的额外相，三元图没有考虑 Ta 和 O，且探测体积超过 as-deposited Sm-Fe-V layer。",
        "跨模态综合",
        "T_材料类_10_6;T_材料类_10_7;T_材料类_11_1",
        "10;11",
        "text",
        "正文解释额外相来源及其对 Figure 9 三元图的影响。",
    ),
    row(
        "Q048",
        "材料类",
        "GPR 预测 coercivity 的结果中，哪些变量与 coercivity 呈正/负相关？",
        "Sm content 与 coercivity 正相关（约 +0.64），Fe content 与 coercivity 负相关（约 -0.65）；α-Fe 对 coercivity 不利，而 V content 有助于稳定 1:12 phase 并有利于 coercivity。",
        "图表理解",
        "T_材料类_11_9;T_材料类_11_10;T_材料类_11_11",
        "11",
        "text;figure",
        "Figure 11 相关段落解释 GPR/correlation matrix 的变量关系。",
    ),
    row(
        "Q049",
        "材料类",
        "为什么作者认为 PCA 不适合作为 XRD 数据的直接物理解释工具，而 NMF 更有优势？",
        "PCA 的正交性约束可能产生难以物理解释的负贡献；NMF 具有 positivity constraint，更适合提取可解释的正成分谱。",
        "文本事实",
        "T_材料类_12_1;T_材料类_12_3",
        "12",
        "text",
        "无监督机器学习部分比较 PCA 和 NMF 的解释性。",
    ),
    row(
        "Q050",
        "材料类",
        "Figure 12 中 NMF components 与 coercivity 的关系如何帮助解释材料相结构？",
        "components 2、3、7 与富 Fe 区域相关并与 coercivity 负相关；component 4 与高 coercivity 区域强正相关；部分与 α-Fe 峰匹配的成分会降低 coercivity。",
        "图文一致性",
        "T_材料类_12_5;T_材料类_12_6;T_材料类_12_8;T_材料类_13_7;T_材料类_13_8",
        "12;13",
        "text;figure",
        "Figure 12 图题、热图和正文解释 NMF 成分与 coercivity 的关系。",
    ),
    row(
        "Q051",
        "环境类",
        "这篇环境论文研究的核心变量 IVFC 是什么，并且如何区分 free-tropospheric 与 boundary-layer IVFC？",
        "IVFC 是 vertically integrated water vapor flux convergence；free-tropospheric IVFC 对 900-300 hPa 积分，boundary-layer IVFC 对 1000-900 hPa 积分。",
        "表格问答",
        "TB_环境类_3_1;T_环境类_3_1",
        "3",
        "table;text",
        "第 3 页公式/方法段落定义了 IVFC 的垂直积分层次。",
    ),
    row(
        "Q052",
        "环境类",
        "摘要和 Key Points 认为 free-tropospheric IVFC 对西日本强降雨有什么作用？",
        "free-tropospheric IVFC 在强降雨前显著增加，为 MAUL 的产生和维持提供有利湿润环境，从而增强 MCS 组织并促进强降雨。",
        "文本事实",
        "T_环境类_1_5;T_环境类_1_7;T_环境类_1_10",
        "1",
        "text",
        "摘要和 Key Points 同时强调 free-tropospheric moisture convergence 的先导作用。",
    ),
    row(
        "Q053",
        "环境类",
        "Figure 1 的时间演变案例中，free-tropospheric IVFC 和 boundary-layer IVFC 谁更早增加？对应的降雨峰值时间是什么？",
        "free-tropospheric IVFC 更早，在 7 月 7 日 03 JST 开始增加；boundary-layer IVFC 在 7 月 8 日 03 JST 增加；降雨峰值为 2016 年 7 月 8 日 12 JST。",
        "图表理解",
        "T_环境类_3_2;T_环境类_4_2;T_环境类_4_3",
        "3;4",
        "text;figure",
        "Figure 1 图题和样例段落给出 IVFC 时间演变与峰值时间。",
    ),
    row(
        "Q054",
        "环境类",
        "Figure 2 的降水分布和垂直剖面说明了什么样的入流与 MAUL 关系？",
        "强而深的入流层（超过 20 m/s、约 5000 m 深）被斜向抬升，MAUL 条件出现在入流层被抬升的区域。",
        "图文一致性",
        "T_环境类_4_4;T_环境类_4_5;T_环境类_5_1;T_环境类_5_2",
        "4;5",
        "text;figure",
        "Figure 2 图题和正文将降水、入流剖面与 MAUL 条件联系起来。",
    ),
    row(
        "Q055",
        "环境类",
        "复合分析中，不同降水强度类别下 free-tropospheric IVFC 的提前量有什么差异？",
        "free-tropospheric IVFC 在所有类别中都早于 boundary-layer IVFC 增加；40-60 mm/day 和超过 60 mm/day 复合中约提前 -39 h，20-40 mm/day 中约提前 -15 h。",
        "图表理解",
        "T_环境类_5_3;T_环境类_5_4;T_环境类_6_1",
        "5;6",
        "text;figure",
        "Figure 3 复合图和正文说明不同强度类别下 IVFC 的提前时间。",
    ),
    row(
        "Q056",
        "环境类",
        "Figure 4 的水平合成图显示边界层与自由对流层水汽通量在峰值前 12 小时有什么空间差异？",
        "峰值前 12 小时，boundary-layer IVFC 主要分布在东海附近，而 free-tropospheric 水汽通量/收敛更接近九州区域，并来自华南和西太平洋方向。",
        "图文一致性",
        "T_环境类_6_3;T_环境类_6_4;T_环境类_6_5;T_环境类_7_1",
        "6;7",
        "text;figure",
        "Figure 4 图题和正文描述水平水汽通量分布及其来源。",
    ),
    row(
        "Q057",
        "环境类",
        "Figure 5 的 MAUL 网格演变结果说明 MAUL 主要出现在哪个高度层，并与什么天气系统有关？",
        "MAUL 网格数增加主要出现在 500-800 hPa，与降水峰值附近发生的 layer-lifting MCSs 有关。",
        "图表理解",
        "T_环境类_7_3;T_环境类_7_5",
        "7",
        "text;figure",
        "Figure 5 相关正文解释 MAUL 网格的高度分布和 MCS 关系。",
    ),
    row(
        "Q058",
        "环境类",
        "研究为什么要剔除峰值附近的热带气旋个例？",
        "如果热带气旋位于九州区域 ±5° 内，相关降水峰值会被剔除，以排除热带气旋直接影响复合结果。",
        "证据定位",
        "T_环境类_4_1",
        "4",
        "text",
        "compositing method 段落说明热带气旋剔除规则。",
    ),
    row(
        "Q059",
        "环境类",
        "MSM 降水资料与 AMeDAS 雨量站资料在文中承担什么关系？",
        "MSM 产生的小时降水用于分析并转换为 3 小时数据，AMeDAS 雨量站数据用于验证 MSM precipitation，且复合降水演变与 AMeDAS 定性一致。",
        "跨模态综合",
        "T_环境类_2_8;T_环境类_6_2;T_环境类_6_3",
        "2;6",
        "text",
        "数据方法和稳健性检验段落共同说明 MSM 与 AMeDAS 的关系。",
    ),
    row(
        "Q060",
        "环境类",
        "结论中作者如何概括 free-tropospheric IVFC、moist environment 和 MCS organization 的因果链条？",
        "free-tropospheric IVFC 在降雨事件前提供湿润环境，湿润环境有利于 MAUL 的产生和维持，进而增强 layer-lifting MCS 的组织并支持强降雨。",
        "跨模态综合",
        "T_环境类_8_3;T_环境类_1_7",
        "1;8",
        "text",
        "摘要和结论共同概括从自由对流层水汽收敛到 MCS 组织的机制链。",
    ),
]


def main() -> None:
    nodes = {node["node_id"] for node in read_jsonl("outputs/parsed/nodes.jsonl") if node.get("node_id")}
    missing: list[tuple[str, str]] = []
    for item in ROWS:
        for node_id in item["gold_node_ids"].split(";"):
            if node_id and node_id not in nodes:
                missing.append((item["question_id"], node_id))
    if missing:
        details = "\n".join(f"{qid}: {node_id}" for qid, node_id in missing)
        raise SystemExit(f"Missing gold node ids:\n{details}")
    write_csv("data/questions.csv", ROWS, QUESTION_FIELDS)
    print(f"Wrote {len(ROWS)} multimodal questions to data/questions.csv")


if __name__ == "__main__":
    main()
